### ISSUE TITLE
Products / Procuct Categories

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#1]
Bug Description: Add Product Categories button has UI issue
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/d96803c2-35e4-4530-b0dc-81bb05902e64)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-01-2024

**Comment by M8Fayaz** [comment]
Pass
