### ISSUE TITLE
Products / Product Upload / Add Product upload button

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#10]
Bug Description: Need to add notes in image field for multiple images.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/4b2c4af4-1b1c-4f8f-9d0c-965180276ea6)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 05-01-24

**Comment by M8Fayaz** [comment]
Pass

**Comment by M8Fayaz** [comment]
Pass
