### ISSUE TITLE
Search / all the modules

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#18]
Bug Description: Search filter having UI issue. while using the search box the system hides all the input fields.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/3743da7b-8ddb-4367-9edc-de306e8fe019)

Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/76056f0d-26d1-4d49-be25-294984caaf9a

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Pass
