### ISSUE TITLE
Book / Appointments

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#25]
Bug Description: There is no dependency screen for message field in admin panel.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/59c40b4b-c9e2-4e2a-af32-d49442dbd1ee)

**Comment by M8Balaji** [comment]
@muthuraja-m8itsolutions  From the API data you will get message value from **message** field, Please and update

**Comment by M8Fayaz** [comment]
Pass
