### ISSUE TITLE
Products / Product

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#28]
Bug Description: Need to change the error message as please select the category name. 
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/ca210a0f-d71e-4aca-a4f0-4abdc94faf25)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Pass

**Comment by M8Fayaz** [comment]
Bug Description: need to validate the name field. Showing an error message for an empty space scenario is good for the user experience.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/2c9e29d8-ed72-4eb4-8bc4-84da34dbb9f2

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
