### ISSUE TITLE
Products / Sub Products

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#29]
Bug Description: Need to change the error message as **please enter the wastage**
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/a719abb6-1013-4e5b-9c43-2bb600dfaeb2)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Pass
