### ISSUE TITLE
Products / Sub Products / Add Sub Product

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#30]
Bug Description: Validate the **Wastage** **length** and **Size** field like Estimated days. showing error message is better way it's good for user experience.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/99bf8704-d09d-400e-88bf-cdb6602aa59c

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Need to validate the **Sub Product** field.

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/5d2325a2-e135-47c9-990f-3bb544197bc0

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
