### ISSUE TITLE
Custome Request / Drop box

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#31]
Bug Description: need to add notes in the drop-down box for multiple uploads. also mention the maximum number of images that can be uploaded.

Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/fa582b28-a543-4186-acd4-8218c68154c9)

**Comment by M8Balaji** [comment]
fixed

**Comment by M8Fayaz** [comment]
Pass
