### ISSUE TITLE
Custom Request / Deleted Message

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#33]
Bug Description: The deleted message has a UI issue; you need to add space between the custom and request.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/ff4e8239-b36c-41c9-93c6-e6a1d25f960f)

**Comment by M8Balaji** [comment]
fixed

**Comment by M8Fayaz** [comment]
Pass
