### ISSUE TITLE
Settings / Banner / Delete

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#34]
Bug Description: Error message showing incorrectly. need to change the **product Categories** as **Banner**
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/641c522c-fc8b-43a6-9825-fd69ed712389)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Pass
