### ISSUE TITLE
Banner / Add New Banner

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#36]
Bug Description: The Weight Range field is unnecessary, we already declare weight in the product upload module. 

Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/da1321be-c173-452e-bf2b-da3ffb388122)

![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/6cd6bc9c-4009-4e2e-9f17-92b4a6ecc799)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09-01-2024

**Comment by M8Fayaz** [comment]
Pass
