### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#38]
Bug Description: Clicking on the Carousel navigation keys should not navigate the user to the product page. navigation keys field should not be navigable.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/10fc4db7-2ef1-4224-9a6c-376a519b02d8

**Comment by M8Balaji** [comment]
fixed

**Comment by M8Fayaz** [comment]
Pass
