### ISSUE TITLE
Settings / option list

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#39]
Bug Description: for empty space, showing an error message is good for the user experience. but the empty space scenario is only showing in Toaster.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/0959cd34-0d9d-4947-973e-9bd6d75bb1d4

**Comment by M8Fayaz** [comment]
Bug Description: need to validate the **Title** field.
If the minimum character length is 5, it means something is mentioned in the error message.

Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/0ccaab7c-337e-40fc-af0c-a859b16a70e7

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
