### ISSUE TITLE
Settings / option list /  Add new option

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#40]
Bug Description: After filling out all the mandatory fields, the system asks for a description in the error message.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/331e9860-34a3-40eb-a5fb-42bf93bdf9c4

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Bug Description: We need to validate the **Title** field. Showing an error message for an empty space scenario is good for the user experience.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/d34126ec-1d7b-4a2e-8e04-63fdea72779a

**Comment by M8Fayaz** [comment]
Pass
