### ISSUE TITLE
Settings / about

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#42]
Bug Description: For empty space, an error message is good for the user experience. the system showing toaster only for empty space scenarios.

Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/e9807ff9-e356-4009-bcbb-52883399f171

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Bug Description: character length is 3 means mentioned in error message. it's good for user experience.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/abe60ace-f08d-4b56-a4a0-522a3a7da01c

**Comment by M8Fayaz** [comment]
Pass
