### ISSUE TITLE
Settings / about / Edit

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#43]
Bug Description: Foundation field should not accept empty space.

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Bug Description: The minimum character length for the title field is 3, which means mention in the error message. It's good for the user experience.
Bug Video:
https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/dec24584-cd6a-4ce5-b9d0-0c1ba66674a5

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
