### ISSUE TITLE
Settings / Tryon / Add Tryon

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#44]
Bug Description: for empty space, showing an error message is good for the user experience. but the empty space scenario is only showing in Toaster.

Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/e247d854-92e5-4dd7-9bac-3ad4025457c3

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Pass
