### ISSUE TITLE
Settings / Tryon / Add Tryon

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#45]
Bug Description: after entering all the Details the system showing **Please provide content** toaster.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/fac85604-9369-40ec-98d1-a33ed2d595fe

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Pass
