### ISSUE TITLE
Store / Main store / Update store

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#47]
Bug Description: **City** field should not accept empty space.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/b04296a1-c002-4376-ab54-93d34ae32343)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 08/01/2024

**Comment by M8Fayaz** [comment]
Pass
