### ISSUE TITLE
Settings / Testimonal / Add new product

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#52]
Bug Description: for empty space, showing an error message is good for the user experience. but the empty space scenario is only showing in Toaster. validate the **name** and **content** field.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/f412d319-3f5c-40d3-a249-c08eec4d6d05

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
