### ISSUE TITLE
Products / Product upload

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#56]
Bug Description: Current rate has UI issue. it's not visible properly.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/f09f3a51-977d-41b5-8db9-31bb5e3d58d5)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
