### ISSUE TITLE
Products / Product upload / Creat new Product Upload or Edit

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#57]
Bug Description: Sub product is not showing sometime. 
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/94c54a7b-bdbb-4840-a4be-abc6112edee2)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
