### ISSUE TITLE
Settings / Banner / Image upload field

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#59]
Bug Description: If there is no image, the system should not show the preview.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/1c211d42-d94a-4873-bf34-7858fc11f600)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
