### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#6]
Bug Description: Log in page has UI issue in the input field.
Bug Screenshot:
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/6fac2cb3-64c4-4fac-b7a1-29a401c59531)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
