### ISSUE TITLE
Settings / About / add or Update About

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#61]
Bug Description: If there is no image, the system should not show the preview.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/e2ae15e0-b88a-478a-94fb-952af2ffdf68)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
