### ISSUE TITLE
Settings / Tryon / Create Tryon

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#62]
Bug Description: If there is no video, the system should not show the preview.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/34f95309-072f-4ba7-87f5-bfa33e663238)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
