### ISSUE TITLE
 Settings / Testimonials/ Add or update Testimonials

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#63]
Bug Description: If there is no image, the system should not show the preview.
Bug screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/f8adf5a1-04e7-45ff-a9c8-1b4976eb5bc0)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
