### ISSUE TITLE
Products / Produt Upload / Creat or edit Product upload

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#65]
Bug Description: Product type field is not showing in User web application.
Bug Screenshot or Screen record: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/a292e6ff-c6ad-433c-bfb2-302bec567654)

**Comment by M8Balaji** [comment]
fixed

**Comment by M8Fayaz** [comment]
Pass
