### ISSUE TITLE
 Products / Produt Upload / Creat or edit Product upload 

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#66]
Bug Description: The system should not show the entire weight range; it should only show the selected weight range in the Gross Weight field.
Bug Screenshot or Screen record: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/99c109c3-2ba4-4002-a626-a8453dfa707e)

![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/d86d621e-7353-4493-943f-80e9513dfd7c)

**Comment by M8Balaji** [comment]
fixed

**Comment by M8Fayaz** [comment]
Pass
