### ISSUE TITLE
About

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#69]
Bug Description: use the valid content
Bug Screenshot or Screen record: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/8988eb71-9fbe-49d4-923f-4afc710ffdcc)

**Comment by M8Balaji** [comment]
fixed

**Comment by M8Fayaz** [comment]
Pass
