### ISSUE TITLE
Products / Product Category

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#71]
Bug Description: some times current rate is not showing.
Bug Screenshot or Screen record: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/66368146-b88a-4834-a49c-809586a0cadb)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
