### ISSUE TITLE
Product page

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#77]
Bug Description: Rate showing incorrectly in the product page
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/98388649-e6b6-4a4a-8162-4b9bf9cbef8a)

![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/aabba8b1-6b23-486a-a704-1ca38795d140)

**Comment by M8Balaji** [comment]
@M8Fayaz  as per the existing formula it giving the value, (Rate * Weight) + Wastage Amount

**Comment by M8Fayaz** [comment]
@M8Balaji 
Rate= 3000
Wight in grams= 3
Wastage in percentage= 10
(3000*3)+300
total amount = **3,300**


but system showing **3100**

**Comment by M8Balaji** [comment]
@M8Fayaz It generates wastage amount only for **1 gram** so The **Wastage Amount = 100**

**Comment by M8Balaji** [comment]
Need to get formula for wastage and amount calculation from BA Team

**Comment by M8Balaji** [comment]
**Now the rate comes correctly**
 Rate per gram= 1000
Wight in grams= 3
Wastage in percentage= 10
(1000*3)+300
total amount = 3,300

**Comment by M8Fayaz** [comment]
Pass
