### ISSUE TITLE
Products / Sub Product

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#8]
Bug Description: Wastage field should not accept empty space.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/469e85fc-7087-426e-999c-d02d6415837b

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 05-01-24

**Comment by M8Fayaz** [comment]
Pass
