### ISSUE TITLE
Contact / Map

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#81]
Bug Description: Map field is not spotting the location of the shop.
Bug Screenshot or Screen record: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/f24e51ff-f194-4077-94bb-88364b017fbe)

**Comment by M8Balaji** [comment]
@M8Fayaz  We had removed the map, Which need additional Api for getting images, Make it as enhancement or close this Issue
