### ISSUE TITLE
Settings / Store / Landlie no

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#83]
Bug Description: Need to validate the Landline no field.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/d32d20a6-35a0-4bd2-8853-f58f7187d55f)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 04-01-2024

**Comment by M8Fayaz** [comment]
Pass
