### ISSUE TITLE
bottom navigation menus / Write to us

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#85]
Bug Description: clicking on the **write to us** will cause **404** error
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/444f257d-e89a-41f0-bcf3-10d36de32fa7

**Comment by M8Balaji** [comment]
Fixed

**Comment by M8Fayaz** [comment]
Pass
