### ISSUE TITLE
bottom navigation menus / Stores / Address

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#86]
Bug Description: Clicking on the Address not spotting the shop location.
Bug Video: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/d635bc43-115c-46bb-8bb8-7eea3fc43448

**Comment by M8Balaji** [comment]
**Not an Issue**,  Need to update the link in admin panel, **I had updated**

**Comment by M8Fayaz** [comment]
not a bug
