### ISSUE TITLE
Products / Product Upload

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#9]
Bug Description: Add Product Upload button had UI issue.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/0ece4499-39be-483b-9bc8-e8b6289e1f4b)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 05-01-24

**Comment by M8Fayaz** [comment]
Pass
