### ISSUE TITLE
Products / Sub Product / Sub Product field

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#95]
Bug Description: Sub product field should not accept empty space, showing error message is good for user experience 
but system showing the popup. also popup having the invalid content.

Bug Screenshot: 

https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/25c55a75-eb54-4e1b-a5e0-f53454720d9a

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024
