### ISSUE TITLE
Products / Product Upload / Add Product upload button 

### ISSUE THREAD

**Issue by M8Fayaz** [M8Fayaz/Kanakalakshmi-Diamonds#96]
Bug Description: The system allows the user to upload more than six images in the image upload field.
Bug Screenshot: 
![image](https://github.com/M8Fayaz/Kanakalakshmi-Diamonds/assets/120467524/2aaaaf76-a8df-41ec-bbdb-d74fcbea51af)

**Comment by muthuraja-m8itsolutions** [comment]
Fixed - 09/01/2024

**Comment by M8Fayaz** [comment]
Pass
